### PR TITLE
don't query on JCR types

### PR DESCRIPTION
**Pull request by acoburn**
See: https://jira.duraspace.org/browse/FCREPO-1765

### CODE REVIEW

**Comment by ajs6f** [comment]
Is the idea here basically to show that we aren't publishing the JCR types?

**Comment by acoburn** [comment]
@ajs6f The upstream changes removed the hasPrimaryType property from the response, so I could either remove this test, invert its logic or add a new test for some different property.

**Comment by ajs6f** [comment]
I say remove it (possibly add a new test if you think it good) because ideally, `fcrepo-transform` will not depend on the existence of the JCR universe, and we don't want to call attention to JCR here.

**Comment by awoods** [comment]
:+1: @ajs6f to removing the JCR-ish test.

**Comment by acoburn** [comment]
The JCR test is now gone.

**Comment by awoods** [comment]
This would  have been a great time to squash/merge :(

**Pull request merged**
