### PR TITLE
remove acoburn from maintainer list

### PR DESCRIPTION
**Pull request by acoburn**
Related to: https://jira.duraspace.org/browse/FCREPO-1672

### CODE REVIEW

**Comment by awoods** [comment]
Let's deprecate this... not abandon it.

**Comment by ajs6f** [comment]
I don't understand this at all. Are you trying to keep @acoburn committed to a project _against his will_? That is utterly and completely unacceptable!

**Comment by acoburn** [comment]
No, fcrepo-transform is a not very useful tool, even in the context of solr indexing-- unless of course ALL of the metadata consists of string literals. Which is not a very good linked data practice. Plus, this module is blocking forward movement of the main code base. I want nothing to do with it.

I already have a camel-based impl that is a million times better.

**Comment by acoburn** [comment]
@awoods fcrepo-transform is deprecated (as of #28). Now, you can remove me from the README. See also the replacement at https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/pull/103

**Comment by awoods** [comment]
@acoburn, It makes perfect sense to remove you from the README given the state of fcrepo-transform and its replacement. The comment I have is around process. There is criteria for a project to qualify for fcrepo4-exts that includes having at least two maintainers. This requirement provides a certain level of assurance to the community that a module has a degree of committed support. A maintainer has every right to revoke their relationship with a module; however, in terms of process, such a revocation should involve more than a pull request to a README. We should talk about what makes sense, but I would suggest a notice to the fedora-tech list that such commitment is being reversed or mention in a Tech meeting or the like.

**Comment by ajs6f** [comment]
That mention in tech meeting has already occurred. You ( @awoods ) weren't in attendance.

**Comment by acoburn** [comment]
IMO this is the proper order:
1. Merge the outstanding fcrepo-camel-toolbox PRs: https://github.com/fcrepo4-exts/fcrepo-camel-toolbox/pulls (all of them)
2. Cut a new fcrepo-camel-toolbox release
3. Announce the deprecation of fcrepo-transform

I would add that fcrepo-camel-toolbox in INCOMPATIBLE with fcrepo-4.6.x. And I cannot/will not work on it until 1 and 2 happen. (That is because there are people currently using fcrepo-camel-\* with 4.5.x releases of Fedora.) I would _really_ appreciate it if someone could review and merge those PRs.

**Comment by ajs6f** [comment]
I can help with the camel-toolbox PRs starting Monday.

**Pull request merged**
